### ISSUE TITLE
Cannot find module 'webpack/lib/WebpackError'

### ISSUE THREAD

**Issue by danbruegge** [cascornelissen/stylelint-bare-webpack-plugin#10]
**Description**
<!-- Clearly and concisely describe the bug, include steps to reproduce -->
After upgrading to 2.1.0. from 2.0.2 there is an `Cannot find module 'webpack/lib/WebpackError'` Error.

**Expected behavior**
<!-- What would you expect to happen? -->
No `Cannot find module 'webpack/lib/WebpackError'` is thrown.

**Actual behavior**
<!-- What is actually happening? -->
After upgrading to version 2.1.0 from 2.0.2 i'll get this error:
```
yarn dev                                                                                                                                                                                                                                                       
yarn run v1.22.4                                                                                                                                                                                                                                               
$ NODE_ENV=dev gatsby develop --port 3000 --host 0.0.0.0                                                                                                                                                                                                       
success open and validate gatsby-configs - 0.015s                                                                                                                                                                                                              
error Error in "/home/dan/workspace/projects/gatsby-plugin-stylelint/gatsby-node.js": Cannot find module 'webpack/lib/WebpackError'                                                                                                                            
Require stack:                                                                                                                                                                                                                                                 
- /home/dan/workspace/projects/gatsby-plugin-stylelint/node_modules/stylelint-bare-webpack-plugin/lib/error.js                                                                                                                                                 
- /home/dan/workspace/projects/gatsby-plugin-stylelint/node_modules/stylelint-bare-webpack-plugin/lib/index.js                                                                                                                                                 
- /home/dan/workspace/projects/gatsby-plugin-stylelint/gatsby-node.js                                                                                                                                                                                          
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js                                                                                                                                             
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js                                                                                                                                              
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/bootstrap/load-plugins/load.js                                                                                                                                                  
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/bootstrap/load-plugins/index.js                                                                                                                                                 
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/services/initialize.js                                                                                                                                                          
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/services/index.js                                                                                                                                                               
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/state-machines/develop/services.js                                                                                                                                              
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/state-machines/develop/index.js                                                                                                                                                 
- /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/commands/develop-process.js                                                                                                                                                     
- /home/dan/workspace/projects/gatsby-starter-minimal/.cache/tmp-56039-NJ8d0KJlYYdQ                                                                                                                                                                            
                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                               
  Error: Cannot find module 'webpack/lib/WebpackError'                                                                                                                                                                                                         
  Require stack:                                                                                                                                                                                                                                               
  - /home/dan/workspace/projects/gatsby-plugin-stylelint/node_modules/stylelint-bare-webpack-plugin/lib/error.js                                                                                                                                               
  - /home/dan/workspace/projects/gatsby-plugin-stylelint/node_modules/stylelint-bare-webpack-plugin/lib/index.js                                                                                                                                               
  - /home/dan/workspace/projects/gatsby-plugin-stylelint/gatsby-node.js                                                                                                                                                                                        
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js                                                                                                                                           
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js                                                                                                                                            
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/bootstrap/load-plugins/load.js                                                                                                                                                
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/bootstrap/load-plugins/index.js                                                                                                                                               
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/services/initialize.js                                                                                                                                                        
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/services/index.js                                                                                                                                                             
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/state-machines/develop/services.js                                                                                                                                            
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/state-machines/develop/index.js                                                                                                                                               
  - /home/dan/workspace/projects/gatsby-starter-minimal/node_modules/gatsby/dist/commands/develop-process.js                                                                                                                                                   
  - /home/dan/workspace/projects/gatsby-starter-minimal/.cache/tmp-56039-NJ8d0KJlYYdQ                                                                                                                                                                          
    - loader.js:725 Function.Module._load                                                                                                                                                                                                                        
    internal/modules/cjs/loader.js:725:27                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
  - loader.js:952 Module.require                                                                                                                                                                                                                               
    internal/modules/cjs/loader.js:952:19                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
  - v8-compile-cache.js:159 require                                                                                                                                                                                                                            
    [gatsby-starter-minimal]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20                                                                                                                                                                            
                                                                                                                                                                                                                                                               
  - error.js:1 Object.<anonymous>                                                                                                                                                                                                                              
    [gatsby-plugin-stylelint]/[stylelint-bare-webpack-plugin]/lib/error.js:1:84                                                                                                                                                                                
                                                                                                                                                                                                                                                               
  - v8-compile-cache.js:178 Module._compile                                                                                                                                                                                                                    
    [gatsby-starter-minimal]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30                                                                                                                                                                            
                                                                                                                                                                                                                                                               
  - loader.js:1092 Object.Module._extensions..js                                                                                                                                                                                                               
    internal/modules/cjs/loader.js:1092:10                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                               
  - loader.js:928 Module.load                                                                                                                                                                                                                                  
    internal/modules/cjs/loader.js:928:32                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
  - loader.js:769 Function.Module._load                                                                                                                                                                                                                        
    internal/modules/cjs/loader.js:769:14                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                               
  - loader.js:952 Module.require                                                                                                                                                                                                                               
    internal/modules/cjs/loader.js:952:19
   
  - v8-compile-cache.js:159 require
    [gatsby-starter-minimal]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
   
  - index.js:7 Object.<anonymous>
    [gatsby-plugin-stylelint]/[stylelint-bare-webpack-plugin]/lib/index.js:7:24
   
  - v8-compile-cache.js:178 Module._compile
    [gatsby-starter-minimal]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30
   
  - loader.js:1092 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1092:10
   
  - loader.js:928 Module.load
    internal/modules/cjs/loader.js:928:32
   
  - loader.js:769 Function.Module._load
    internal/modules/cjs/loader.js:769:14
   

not finished load plugins - 0.400s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**System information**
<!-- Execute the following command and include the output -->
```npx envinfo --system --binaries --npmPackages                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
  System:                                                                                                                                                                                                                                                      
    OS: Linux 5.9 Arch Linux                                                                                                                                                                                                                                   
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz                                                                                                                                                                                                      
    Memory: 10.62 GB / 31.03 GB                                                                                                                                                                                                                                
    Container: Yes                                                                                                                                                                                                                                             
    Shell: 5.0.18 - /bin/bash                                                                                                                                                                                                                                  
  Binaries:                                                                                                                                                                                                                                                    
    Node: 14.15.1 - /usr/bin/node
    Yarn: 1.22.4 - ~/.npm-global/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
  npmPackages:
    @danbruegge/gatsby-plugin-stylelint: ^4.1.0 => 4.1.0 
    @graphql-codegen/cli: ^1.19.4 => 1.19.4 
    @graphql-codegen/typescript: ^1.19.0 => 1.19.0 
    @graphql-codegen/typescript-operations: ^1.17.12 => 1.17.12  
    @testing-library/jest-dom: ^5.11.6 => 5.11.6 
    @testing-library/react: ^11.2.2 => 11.2.2 
    @types/jest: ^26.0.16 => 26.0.16 
    @types/react: ^17.0.0 => 17.0.0 
    @types/react-dom: ^17.0.0 => 17.0.0 
    @types/react-helmet: ^6.1.0 => 6.1.0 
    @types/styled-components: ^5.1.4 => 5.1.4 
    @types/styled-system: ^5.1.10 => 5.1.10 
    @typescript-eslint/eslint-plugin: ^4.9.0 => 4.9.0 
    @typescript-eslint/parser: ^4.9.0 => 4.9.0 
    babel-jest: ^26.6.3 => 26.6.3 
    babel-preset-gatsby: ^0.8.0 => 0.8.0 
    eslint: ^7.2.0 => 7.15.0 
    eslint-config-prettier: ^7.0.0 => 7.0.0 
    eslint-loader: 4.0.2 => 4.0.2 
    eslint-plugin-jest: ^24.1.3 => 24.1.3 
    eslint-plugin-jest-dom: ^3.6.3 => 3.6.3 
    eslint-plugin-jsx-a11y: ^6.2.3 => 6.4.1 
    eslint-plugin-prettier: ^3.1.3 => 3.2.0 
    eslint-plugin-react: ^7.20.0 => 7.21.5 
    gatsby: ^2.28.0 => 2.28.0 
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8 
    gatsby-plugin-manifest: ^2.8.0 => 2.8.0 
    gatsby-plugin-offline: ^3.6.0 => 3.6.0 
    gatsby-plugin-react-helmet: ^3.6.0 => 3.6.0 
    gatsby-plugin-styled-components: ^3.6.0 => 3.6.0 
    gatsby-plugin-typescript: ^2.8.0 => 2.8.0 
    graphql: ^15.1.0 => 15.4.0 
    identity-obj-proxy: 3.0.0 => 3.0.0 
    jest: ^26.6.3 => 26.6.3 
    prettier: ^2.2.1 => 2.2.1 
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
    react-helmet: ^6.1.0 => 6.1.0 
    styled-components: ^5.2.1 => 5.2.1 
    styled-system: 5.1.5 => 5.1.5 
    stylelint: ^13.8.0 => 13.8.0 
    stylelint-config-recommended: 3.0.0 => 3.0.0 
    stylelint-config-styled-components: 0.1.1 => 0.1.1 
    stylelint-processor-styled-components: ^1.10.0 => 1.10.0 
    typescript: ^4.1.2 => 4.1.2
```

**Minimal reproduction**
<!-- Including a minimal repository that reproduces the problem helps a lot with debugging -->
- Clone: `https://github.com/danbruegge/gatsby-plugin-stylelint`
- Update stylelint-bare-webpack-plugin to current version
- Link package
- Clone: `https://github.com/danbruegge/gatsby-starter-minimal`
- Link: `danbruegge/gatsby-plugin-stylelint`
- Run: `yarn dev`

**Additional context**
<!-- Include any other relevant details (e.g. related issues) here -->

**Comment by cascornelissen** [comment]
Interesting, I don't have much knowledge on Gatsby and its plugin system but what is the webpack version behind your setup? I've tried checking out `danbruegge/gatsby-starter-minimal` but `npm ls webpack` is not returning anything 🤔

**Comment by cascornelissen** [comment]
Ping @danbruegge

**Comment by danbruegge** [comment]
The project uses mostly the gatsbyjs defaults. Here you can see what i have modified:
```js
const path = require("path");

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      alias: {
        "-": path.resolve(__dirname, "src"),
      },
      modules: ["node_modules"],
    },
  });
};
```
https://github.com/danbruegge/gatsby-starter-kitt/blob/master/gatsby-node.js

**Comment by cascornelissen** [comment]
For some context: the stacktrace you're seeing is because the plugin is unable to find a file that's part of the `webpack` package. 

When cloning either of the URLs you included in the original post, then installing the dependencies using `npm install`, and then running `npm ls webpack`, it doesn't show any installed version of Webpack which explains why the plugin can't find the file.

Since I have no experience on how Gatsby works internally, and I'm seeing no references to the `webpack` npm package in your stacktraces either it looks like you don't have webpack installed? I'm guessing `npm install --save-dev webpack` will solve your issue but I'm baffled by how Gatsby is able to compile everything while Webpack is not installed...
