### PR TITLE
Fixes #1 Missing stylelint formatter not being found throws error

### LINKED ISSUE #1: Does not work with stylelint 7.7.0
Stylelint 7.7.0 does not contain the dist directory anymore. So 'stylelint/dist/formatters/stringFormatter' cannot be loaded.

https://github.com/stylelint/stylelint/compare/7.6.0...7.7.0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

```
Message:
    Cannot find module 'stylelint/dist/formatters/stringFormatter'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'stylelint/dist/formatters/stringFormatter'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at new StylelintBarePlugin (/projects/freshheads-administratie/node_modules/stylelint-bare-webpack-plugin/stylelint-bare.js:21:20)
    at createWebpackOptions (/projects/freshheads-administratie/node_modules/fh-gulp-task/lib/task/webpack.js:129:13)
    at build (/projects/freshheads-administratie/node_modules/fh-gulp-task/lib/task/webpack.js:163:19)
    at /projects/freshheads-administratie/node_modules/fh-gulp-task/lib/task/webpack.js:186:9
    at /projects/freshheads-administratie/node_modules/lodash/lodash.js:4970:15
    at Function.forIn (/projects/freshheads-administratie/node_modules/lodash/lodash.js:12921:11)
```

### PR DESCRIPTION
**Pull request by cascornelissen**

### CODE REVIEW

**Review by gijsvanzon — APPROVED** [review]

**Review by jvandesande — CHANGES_REQUESTED** [review]
You can use the public API of stylelint to fetch the formatter:
https://github.com/vieron/stylelint-webpack-plugin/commit/35f5d72836044e3c8738072af3f88f9c3c15a029

**Comment by cascornelissen** [comment]
@jvandesande, nice find; I'll check if that works!

**Comment by cascornelissen** [comment]
@jvandesande, looks like this was added in `7.7.0`, as it's not available in [`7.6.0`](https://github.com/stylelint/stylelint/blob/7.6.0/src/index.js). I'll include the moduleAvailable method for older versions

**Review by gijsvanzon — APPROVED** [review]
There are a few older versions. But it's ok not to check for them

**Review by jvandesande — APPROVED** [review]
